

import java.sql.*; 
import javax.swing.*;    
import java.awt.event.*;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author himanshu
 */
public class ActivityPage extends javax.swing.JFrame {

    /**
     * Creates new form ActivityPage
     */
    Connection con;
    static int c_id=1000;
    public ActivityPage() {
        
        initComponents();
         
        try{  
Class.forName("com.mysql.jdbc.Driver");  
            con= DriverManager.getConnection(  
"jdbc:mysql://localhost:3306/DigitalBillingSystem?zeroDateTimeBehavior=convertToNull","root","");  


Statement stmt=con.createStatement();  
/*String sqli="insert into customer values('amit');";
stmt.executeUpdate(sqli);*/
//con.close();  
}catch(Exception e){ System.out.println(e);}  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        c_contact_txtF = new javax.swing.JTextField();
        c_name_txtF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pricetxtfield = new javax.swing.JTextField();
        availTxtfield = new javax.swing.JTextField();
        ItemsComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        QtySpinner = new javax.swing.JSpinner();
        addbtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        edittxtfield = new javax.swing.JButton();
        removetxtfield = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cartTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        totalAmtTxtfield = new javax.swing.JTextField();
        calcbtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        okbtn = new javax.swing.JButton();
        cstIDtxtfield = new javax.swing.JTextField();
        cancelbtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        paid_amt_txtF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(240, 242, 242));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Customer's Details"));

        jLabel3.setText("Customer's Contact :");

        jLabel1.setText("Customer's Name:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(c_contact_txtF)
                    .addComponent(c_name_txtF, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(c_name_txtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(c_contact_txtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(240, 242, 242));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Items Detail"));

        jLabel6.setText("Availability:");

        pricetxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pricetxtfieldActionPerformed(evt);
            }
        });

        availTxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availTxtfieldActionPerformed(evt);
            }
        });

        ItemsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laptop", "CPU", "Data Cable", "Charger", "Pen Drive", "Mouse", "Keyboard", "UPS", "Antivirus" }));
        ItemsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemsComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Purchased Items:");

        jLabel7.setText("Price:");

        jLabel4.setText("Qty :");

        QtySpinner.setModel(new javax.swing.SpinnerNumberModel(0, null, 10000000, 1));

        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QtySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ItemsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel6)))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(availTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addbtn))
                .addGap(4, 4, 4)
                .addComponent(jLabel7)
                .addGap(1, 1, 1)
                .addComponent(pricetxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ItemsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(availTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(pricetxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(QtySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addbtn))
                    .addComponent(jLabel4))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(240, 242, 242));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Items in Cart"));

        edittxtfield.setText("Edit");
        edittxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edittxtfieldActionPerformed(evt);
            }
        });

        removetxtfield.setText("Remove");
        removetxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removetxtfieldActionPerformed(evt);
            }
        });

        cartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Qty", "Price", "Discount", "Tax", "Amount"
            }
        ));
        jScrollPane1.setViewportView(cartTable);
        cartTable.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(edittxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removetxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edittxtfield)
                    .addComponent(removetxtfield))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(240, 242, 242));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Payment Details:"));

        calcbtn.setText("Calculate");
        calcbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcbtnActionPerformed(evt);
            }
        });

        jLabel8.setText("Customer's ID:");

        jLabel5.setText("Total Amount :");

        okbtn.setText("OK");
        okbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbtnActionPerformed(evt);
            }
        });

        cstIDtxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cstIDtxtfieldActionPerformed(evt);
            }
        });

        cancelbtn.setText("Cancel");
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        jLabel9.setText("Paid Amount :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cancelbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(totalAmtTxtfield)
                    .addComponent(cstIDtxtfield)
                    .addComponent(paid_amt_txtF))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(calcbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(okbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resetBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(totalAmtTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(calcbtn)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paid_amt_txtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cstIDtxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelbtn)
                    .addComponent(okbtn)
                    .addComponent(resetBtn))
                .addContainerGap())
        );

        jButton1.setText("Exit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edittxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edittxtfieldActionPerformed
     
        
        for(int i=0;i<cartTable.getRowCount();i++)
        {
           String z1=cartTable.getValueAt(i, 2).toString();
          String z2=cartTable.getValueAt(i, 3).toString();
          String z3=cartTable.getValueAt(i, 4).toString();
          String z4=cartTable.getValueAt(i, 1).toString();
          System.out.println(z1+" "+z2+" "+z3+" "+z4);
          double dprice=Double.parseDouble(z1);
            double dDiscount=Double.parseDouble(z2);
              double dTax=Double.parseDouble(z3);
                double dQty=Double.parseDouble(z4);
                double fvalue=dQty*(dprice*(1+dTax/100-dDiscount/100));
                cartTable.setValueAt(fvalue, i, 5);
                
        }
        
    }//GEN-LAST:event_edittxtfieldActionPerformed

    private void cstIDtxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cstIDtxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cstIDtxtfieldActionPerformed

    private void ItemsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemsComboBoxActionPerformed
       String s=String.valueOf(ItemsComboBox.getSelectedItem());
       try{  
        Statement stmt=con.createStatement();
        
        ResultSet rs=stmt.executeQuery("select * from items where items.name='"+s+"';");  
       while(rs.next())  
       {
        System.out.println(rs.getString("qty")+"  "+rs.getString("price"));
        availTxtfield.setText(rs.getString("qty"));
        pricetxtfield.setText(rs.getString("price"));
       }
        }
       catch(Exception e){ System.out.println(e);} 
    }//GEN-LAST:event_ItemsComboBoxActionPerformed

    private void availTxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availTxtfieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_availTxtfieldActionPerformed

    private void pricetxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pricetxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pricetxtfieldActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        String s= String.valueOf(ItemsComboBox.getSelectedItem());
        String price="",tax="",discount="";
        Object  priceO,taxO,discountO;
        try{  
        Statement stmt=con.createStatement();
        
        ResultSet rs=stmt.executeQuery("select * from items where items.name='"+s+"';");  
       while(rs.next())  
       {
       tax=rs.getString("tax");
       discount=rs.getString("discount");
       price=rs.getString("price");
      
       }
     
        }
       catch(Exception e){ System.out.println(e);}
        String z=QtySpinner.getValue().toString();
        double qt=Double.parseDouble(z);
        taxO=tax;
        discountO=discount;
        priceO=price;
        double one=1;
        //System.out.println((one-(Double.parseDouble(discount)/100)+(Double.parseDouble(tax)/100)));
        Object amountO=qt*((one-(Double.parseDouble(discount)/100)+(Double.parseDouble(tax)/100))*(Double.parseDouble(price)));
        DefaultTableModel model= (DefaultTableModel)cartTable.getModel();
        model.addRow(new Object[]{ItemsComboBox.getSelectedItem(),QtySpinner.getValue(),priceO,discountO,taxO,amountO});
    }//GEN-LAST:event_addbtnActionPerformed

    private void calcbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcbtnActionPerformed
        double amt=0;
        for(int i=0;i<cartTable.getRowCount();i++)
        {
           String z1=cartTable.getValueAt(i, 5).toString();
           amt+=(Double.parseDouble(z1));
        }
      totalAmtTxtfield.setText(Double.toString(amt));
    }//GEN-LAST:event_calcbtnActionPerformed

    private void removetxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removetxtfieldActionPerformed
        // TODO add your handling code here:
         int viewIndex = cartTable.getSelectedRow();
    if(viewIndex != -1) {
        int modelIndex = cartTable.convertRowIndexToModel(viewIndex); // converts the row index in the view to the appropriate index in the model
        DefaultTableModel model = (DefaultTableModel)cartTable.getModel();
        model.removeRow(modelIndex);
    }
    }//GEN-LAST:event_removetxtfieldActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        totalAmtTxtfield.setText("");
        paid_amt_txtF.setText("");
        cstIDtxtfield.setText("");
        availTxtfield.setText("");
        pricetxtfield.setText("");
        c_name_txtF.setText("");
        c_contact_txtF.setText("");
        DefaultTableModel model = (DefaultTableModel) cartTable.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_resetBtnActionPerformed

    private void okbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okbtnActionPerformed
         String cname = c_name_txtF.getText().toString();
         String contact = c_contact_txtF.getText().toString();
         String purchasedamt="0",cr="0",debt="0";
         double totalamt=Double.parseDouble(totalAmtTxtfield.getText().toString());
          double paidamt=Double.parseDouble(paid_amt_txtF.getText().toString());
          String paidamtS=Double.toString(paidamt);
         double crdtI=(paidamt>totalamt)?(paidamt-totalamt):0;
          double debtI=(paidamt<totalamt)?(-paidamt+totalamt):0;
         String crdt=Double.toString(crdtI);
         String dbt=Double.toString(debtI);
          try{  
        Statement stmt=con.createStatement();
        
        ResultSet rs=stmt.executeQuery("select * from customer where customer.contact='"+contact+"';");  
       while(rs.next())  
       {
        System.out.println(rs.getString("id"));
        cstIDtxtfield.setText(rs.getString("id"));
        purchasedamt=rs.getString("purchased_amt");
        cr=rs.getString("credit");
        debt=rs.getString("debit");
       }
        }
       catch(Exception e){ System.out.println(e);}
          //new customer
         if (cstIDtxtfield.getText().equals("")){
            c_id+=1;
            String ci_d=String.valueOf(c_id);
            cstIDtxtfield.setText(ci_d);
            //inserting new customer into customer table 
               try{  
        String qry ="INSERT INTO customer  VALUES ('"+ci_d+"', '"+cname+"','"+contact+"','"+paidamtS+"','"+dbt+"','"+crdt+"')";
        PreparedStatement stmt=con.prepareStatement(qry);
        int i=stmt.executeUpdate();  
        System.out.println(i+" records inserted"); 
        }
       catch(Exception e){ System.out.println(e);}
              
             //Fetching items from Jtable
                 DefaultTableModel dtm = (DefaultTableModel) cartTable.getModel();
    int nRow = dtm.getRowCount(), nCol = dtm.getColumnCount();
    String[][] tableData = new String[nRow][2];
    for (int i = 0 ; i < nRow ; i++)
        for (int j = 0 ; j < 2 ; j++)
        {
            tableData[i][j] = dtm.getValueAt(i,j).toString();
        }
    //updating table items
    for(int i=0;i<nRow;i++){
           try{  
        Statement stmt=con.createStatement();
        
        ResultSet rs=stmt.executeQuery("select * from items where items.name='"+tableData[i][0]+"';");  
       while(rs.next())  
       {
           
        int availableItem=Integer.parseInt(rs.getString("qty"));
            int reducedBy=Integer.parseInt(tableData[i][1]);
            
                  try{  
                      PreparedStatement stmt2=con.prepareStatement("update items set qty=? where name=?");  
                        stmt2.setString(1,Integer.toString(availableItem-reducedBy));//1 specifies the first parameter in the query i.e. name  
                        stmt2.setString(2,tableData[i][0]);
        int k = stmt2.executeUpdate();  
        System.out.println(k+" records updated"); 
        }
       catch(Exception e){ System.out.println(e);}
       }
     
        }
       catch(Exception e){ System.out.println(e);}
    }
    //updating customer's total amount purchased by the customer 
           try{  
                        PreparedStatement stmt=con.prepareStatement("update customer set purchased_amt=?,debit=?,credit=? where contact=?");  
                         stmt.setString(1,paidamtS);//1 specifies the first parameter in the query i.e. name  
                        
                        double updatedDbt=Double.parseDouble(debt)+debtI;
                         stmt.setString(2,Double.toString(updatedDbt));
                         double updatedCr=Double.parseDouble(cr)+crdtI;
                         stmt.setString(3,Double.toString(updatedCr));
                         stmt.setString(4,contact);
        int k = stmt.executeUpdate();  
        System.out.println(k+" records updated"); 
        }
       catch(Exception e){ System.out.println(e);} 
         }
         //old customer
         else{
             //Fetching items from Jtable
                 DefaultTableModel dtm = (DefaultTableModel) cartTable.getModel();
    int nRow = dtm.getRowCount(), nCol = dtm.getColumnCount();
    String[][] tableData = new String[nRow][nCol];
    for (int i = 0 ; i < nRow ; i++)
        for (int j = 0 ; j < 2 ; j++)
        {
            tableData[i][j] = dtm.getValueAt(i,j).toString();
        }
    //updating table items
    for(int i=0;i<nRow;i++){
           try{  
        Statement stmt=con.createStatement();
        
        ResultSet rs=stmt.executeQuery("select * from items where items.name='"+tableData[i][0]+"';");  
       while(rs.next())  
       {
           
        int availableItem=Integer.parseInt(rs.getString("qty"));
            int reducedBy=Integer.parseInt(tableData[i][1]);
            
                  try{  
                      PreparedStatement stmt2=con.prepareStatement("update items set qty=? where name=?");  
                        stmt2.setString(1,Integer.toString(availableItem-reducedBy));//1 specifies the first parameter in the query i.e. name  
                        stmt2.setString(2,tableData[i][0]);
        int k = stmt2.executeUpdate();  
        System.out.println(k+" records updated"); 
        }
       catch(Exception e){ System.out.println(e);}
       }
     
        }
       catch(Exception e){ System.out.println(e);}
    }
    //updating customer's total  purchase
           try{     
               PreparedStatement stmt=con.prepareStatement("update customer set purchased_amt=purchased_amt+?,debit=?,credit=? where contact=?");  
                         stmt.setString(1,paidamtS);//1 specifies the first parameter in the query i.e. name  
                       
                         double updatedDbt=Double.parseDouble(debt)+debtI-Double.parseDouble(cr)-crdtI;
                         if(updatedDbt>0)
                         stmt.setString(2,Double.toString(updatedDbt));
                         else
                            stmt.setString(2,"0"); 
                         double updatedCr=Double.parseDouble(cr)+crdtI-Double.parseDouble(debt)-debtI;
                         if(updatedCr>0)
                         stmt.setString(3,Double.toString(updatedCr));
                         else
                         stmt.setString(3,"0");  
                         stmt.setString(4,contact);
        int k = stmt.executeUpdate();  
        System.out.println(k+" records updated"); 
        }
       catch(Exception e){ System.out.println(e);} 
           // checking customer's debit & credit records
            try{  
        Statement stmt=con.createStatement();
        
        ResultSet rs=stmt.executeQuery("select * from customer where customer.contact='"+contact+"';");  
       while(rs.next())  
       {
        System.out.println("customer debts="+rs.getString("debit"));
        double p_amt=Double.parseDouble(rs.getString("purchased_amt"));
        if(!(rs.getString("debit").equals("0"))){
         JFrame f;  
                    f=new JFrame();  
    JOptionPane.showMessageDialog(f,"This customer has  ₹ "+rs.getString("debit")+" lending");
       }
        else if(!(rs.getString("credit").equals("0"))){
            JFrame f;  
                    f=new JFrame(); 
    JOptionPane.showMessageDialog(f,"This customer has  ₹ "+rs.getString("credit")+" credits");
    
        }
        else if(p_amt%10000==0){
            JFrame f;  
                    f=new JFrame(); 
    JOptionPane.showMessageDialog(f,"This customer has completed the purchase of ₹ "+rs.getString("purchsed_amt")+" ,and he/she deserves a prize");
    
        }
       }
        }
       catch(Exception e){ System.out.println(e);}
         }
    }//GEN-LAST:event_okbtnActionPerformed

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActivityPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActivityPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActivityPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActivityPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActivityPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ItemsComboBox;
    private javax.swing.JSpinner QtySpinner;
    private javax.swing.JButton addbtn;
    private javax.swing.JTextField availTxtfield;
    private javax.swing.JTextField c_contact_txtF;
    private javax.swing.JTextField c_name_txtF;
    private javax.swing.JButton calcbtn;
    private javax.swing.JButton cancelbtn;
    private javax.swing.JTable cartTable;
    private javax.swing.JTextField cstIDtxtfield;
    private javax.swing.JButton edittxtfield;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okbtn;
    private javax.swing.JTextField paid_amt_txtF;
    private javax.swing.JTextField pricetxtfield;
    private javax.swing.JButton removetxtfield;
    private javax.swing.JButton resetBtn;
    private javax.swing.JTextField totalAmtTxtfield;
    // End of variables declaration//GEN-END:variables
}
